### ISSUE TITLE
Change Refit to RestEase

### ISSUE THREAD

**Issue by dannythunder** [nagybalint001/keycloak.client#8]
Refit is pretty much dead. A transition to RestEase would keep this project more up to date.

Creating a fork, and creating a PR soon.

**Comment by dannythunder** [comment]
[The PR](https://github.com/nagybalint001/keycloak.client/pull/9)

**Comment by dannythunder** [comment]
Closed the PR, I'm trying to configure Keycloak and this lib to work together

**Comment by nagybalint001** [comment]
Thank you for your contribution @dannythunder, but I have not seen any official statement about the deprecation of refit. 
Right now I'm not convinced to change it. Also the Restease uses newtonsoft json, meanwhile refit could work with both newtonsoft json and system.text.json.

Do you know any official news about refit? Or you just came to this conclusion by the time of the last release and issue count?

**Comment by dannythunder** [comment]
Not official, but the extremley slow updates are of concern, I'll use your code as base and release a private nuget for testing 👍 

Closing this.

**Comment by tibitoth** [comment]
https://github.com/reactiveui/refit/releases/tag/6.4.1
